#! /bin/bash

# You've got to be root to do this -
# it depends on the eee_tarball being located in /root/

setup=${1:-/root/eee-setup}

moddir=/lib/modules/`uname -r`/kernel/drivers/net/atl2
mkdir -p ${moddir}
cp ${setup}/atl2/atl2.ko $moddir}/
/sbin/depmod -a

# Do this as a force since the mirror repo in the ks 
# may have a slightly dated kernel (no big deal)
/sbin/modprobe -f atl2 
