#! /bin/bash

setup=${1:-/root/eee-setup}
liveuser=${2:-eeedora}

# Create a .xsession (for startx users)
xsession=/home/${liveuser}/.xsession
cp ${setup}/xfce/dot-xsession ${xsession}
chmod a+x ${xsession} 
chown ${liveuser}:${liveuser} ${xsession}

# Create a .xinit (for whom ?)
xinitrc=/home/${liveuser}/.xinitrc
cp ${setup}/xfce/dot-xinitrc ${xinitrc}
chmod a+x ${xinitrc}
chown ${liveuser}:${liveuser} ${xinitrc}

# ShowProgress "Copy over my beautiful XFCE settings to ${liveuser}"
# Create this with :
# tar -czf eeedora-dot-config.tar.gz /home/${liveuser}/.config
tar -xzf ${setup}/xfce/eeedora-dot-config.tar.gz -C /home/${liveuser}/

chown -R ${liveuser}:${liveuser} /home/${liveuser}/
