#! /bin/bash

# This takes the kernel module from here (.) ; builds an rpm around it, which it leaves here

driverver=0.1.0.0

#cp atl2-${driverver}.tar.gz /usr/src/redhat/SOURCES/
#tar -xzf atl2-${driverver}.tar.gz
#rpmbuild -tb atl2-${driverver}/atl2-eee.spec

# Build the build directory directly
mkdir atl2_eee-${driverver}/
cp ./atl2_eee.spec atl2_eee-${driverver}/
cp ./atl2.ko atl2_eee-${driverver}/

# Make it into an RPM
tar -czf atl2_eee-${driverver}.tar.gz atl2_eee-${driverver}
rpmbuild -tb atl2_eee-${driverver}.tar.gz 
rm -f atl2_eee-${driverver}.tar.gz
rm -rf atl2_eee-${driverver}

cp /usr/src/redhat/RPMS/i386/atl2_eee-${driverver}-1.i386.rpm .

#rm -rI atl2-${driverver}
