#! /bin/bash

svn checkout svn://svn.berlios.de/linux-uvc/linux-uvc/trunk

pushd .

cd trunk/
make
popd

cp trunk/uvcvideo.ko .


exit

# Install lucview
yum install SDL SDL-devel

tar -xzf 
cd 
make

# This stuff installs from the Asus source - may not cooperate with Fedora much though
pushd .

# this rar file is what Asus released
unrar x Uvcvideo_Source_071127.rar 
tar -xzf uvcvideo_20070706-4.tar.gz 

# This is the meat of it
cd uvcvideo
tar -xzf uvcvideo.tar.gz 
cd uvcvideo
make
cp *.ko ../../
popd

# Clean up
rm -rf uvcvideo uvcvideo_20070706-4.*
