#! /bin/bash

if ! true; then 
	svn checkout svn://svn.berlios.de/linux-uvc/linux-uvc/trunk
	pushd .

	cd trunk/
	make
	popd

	cp trunk/uvcvideo.ko uvcvideo.ko-svn
	cp uvcvideo.ko-svn uvcvideo.ko
else
	# This stuff installs from the Asus source - may not cooperate with Fedora much though
	pushd .

	# this rar file was released by Asus 
	unrar x Uvcvideo_Source_071127.rar 
	tar -xzf uvcvideo_20070706-4.tar.gz 

	# This is the meat of it
	cd uvcvideo
	tar -xzf uvcvideo.tar.gz 
	cd uvcvideo
	make clean
	make 
	cp *.ko ../../uvcvideo.ko-asus
	popd

	cp uvcvideo.ko-asus uvcvideo.ko

 # Clean up
	rm -rf uvcvideo uvcvideo_20070706-4.*
fi

# Build lucview
if ! true; then 
	yum install SDL SDL-devel
 
	pushd .
 tar -xzf luvcview-20070512.tar.gz
	cd luvcview-20070512
	make clean
	make
	cp luvcview ../
 popd
fi
