#!/bin/bash
#
# live: Init script for live image
#
# chkconfig: 345 00 99
# description: Init script for live image.

liveuser="eeedora"

# This has already been unwrapped (in the ISO kickstart code)
setup=/root/eee-setup

ShowProgress() {
 echo $"init.d.fedora-nonlive : $1" >> /etc/eeedora.progress
}

ShowProgress "Loading /etc/init.d/functions"
. /etc/init.d/functions

exists() {
 which $1 >/dev/null 2>&1 || return
 $*
}

#ShowProgress "Testing cmdline - go no further if not a live image"
#if ! strstr "`cat /proc/cmdline`" liveimg || [ "$1" != "start" ] || [ -e /.liveimg-configured ] ; then
# ShowProgress "Apparently this was not a live image"
# exit 0
#fi

ShowProgress "TODO : Fix up /etc/fstab (not done)"
# Use sed to fix up /etc/fstab (like the gdm.conf below)


# TODO : Fix up fstab - now we know we're on the internal /dev/sda drive
# TODO : Fix up logging 


#ShowProgress "Touching liveimg-configured"
#touch /.liveimg-configured

#ShowProgress "Mount live image"
#if [ -b /dev/live ]; then
# mkdir -p /mnt/live
# mount -o ro /dev/live /mnt/live
#fi

if ! [ 1 ]; then # DISABLE CREATION OF SWAP PARTITION - SAVE FLASH RAM OVERWRITES
 ShowProgress "Enable swaps unless requested otherwise"
 # This is the list of current swap partitions
 swaps=`blkid -t TYPE=swap -o device`
 if ! strstr "`cat /proc/cmdline`" noswap -a [ -n "$swaps" ] ; then
  # Go through the list until we get a hit...
  for s in $swaps ; do
    action "Enabling swap partition $s" swapon $s
  done
 fi
else
 ShowProgress "Eee has swap disabled"
fi

# TODO : cpu scaling : This would increase battery time
# echo ondemand > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
# Default state for Eee :
# echo performance > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor


#ShowProgress "Configure X, allowing user to override xdriver"
#for o in `cat /proc/cmdline` ; do
#	case $o in
#	xdriver=*)
#		xdriver="--set-driver=${o#xdriver=}"
#		;;
#	esac
#done

#ShowProgress "system-config-display ($xdriver)"
#exists system-config-display --noui --reconfig --set-depth=24 $xdriver

#ShowProgress "Unmute sound card"
#exists alsaunmute 0 2> /dev/null

#ShowProgress "Turn off firstboot for livecd boots"
#echo "RUN_FIRSTBOOT=NO" > /etc/sysconfig/firstboot

#ShowProgress "Add useful repos"
#cp ${setup}/repos/* /etc/yum.repos.d/

#ShowProgress "Don't start yum-updatesd for livecd boots"
chkconfig --level 345 yum-updatesd off

#ShowProgress "Don't start cron/at as they tend to be painful in a Live context"
# don't start cron/at as they tend to spawn things which are
# disk intensive that are painful on a live image
#chkconfig --level 345 crond off
#chkconfig --level 345 atd off
#chkconfig --level 345 anacron off
#chkconfig --level 345 readahead_early off
#chkconfig --level 345 readahead_later off

#ShowProgress "Stopgap fix for RH #217966; should be fixed in HAL instead"
#touch /media/.hal-mtab

# disable screensaver locking
#gconftool-2 --direct --config-source=xml:readwrite:/etc/gconf/gconf.xml.defaults -s -t bool /apps/gnome-screensaver/lock_enabled false >/dev/null

#
# Now do all the stuff for the special new eeedora user
#

#ShowProgress "Add '${liveuser}' user with no passwd"
#useradd -c "Eeedora Live" ${liveuser}
#passwd -d ${liveuser} > /dev/null

#ShowProgress "Process display manager options"
#${setup}/xdm/setup-display-manager ${setup} ${liveuser}

#ShowProgress "Set up XFCE for '${liveuser}'"
#${setup}/xfce/setup-xfce ${setup} ${liveuser}

#ShowProgress "Add a desktop link to install the live image for '${liveuser}'"
#ln -s ${setup}/live-install/eee-live-install /home/andrewsm/Desktop/Install-Live-Image

# Remove Desktop link to this file the live installation
rm -f ${liveuser}/Desktop/Install-Live-Image


# Do this permission setting last - 

ShowProgress "Set User permissions - Can be removed once the ui hacks have gone"
chown -R ${liveuser}:${liveuser} /home/${liveuser}/
chmod 700 /home/${liveuser}/

ShowProgress "/sbin/restorecon for ${liveuser} home directory"
/sbin/restorecon -R /home/${liveuser}/
chmod 700 /home/${liveuser}/
