#! /bin/bash

driverver=1.0.40.4
rel=2

#cp atl2-${driverver}.tar.gz /usr/src/redhat/SOURCES/
#tar -xzf atl2-${driverver}.tar.gz
#rpmbuild -tb atl2-${driverver}/atl2-eee.spec

rpmbuild -tb atl2-${driverver}.tar.gz

cp /usr/src/redhat/SRPMS/atl2-${driverver}-${rel}.src.rpm .
cp /usr/src/redhat/RPMS/i386/atl2-${driverver}-${rel}.i386.rpm .
cp /usr/src/redhat/RPMS/i386/atl2-debuginfo-${driverver}-${rel}.i386.rpm .

#rm -rI atl2-${driverver}
