#! /bin/bash

./build_generic_rpm wicd
./build_generic_rpm madwifi
./build_generic_rpm scitepm
./build_generic_rpm eee-acpi
./build_generic_rpm truecrypt

# ./build_generic_rpm eee-user-defaults
#  = /etc/skel *

# Elsewhere
#  - /etc/sysconfig/desktop

# boost 
#  - (needs bjam?) - maybe just let Fedora team do this one

