#! /bin/bash

./build_generic_rpm wicd

# Don't need (?) in FC10
## ./build_generic_rpm madwifi

./build_generic_rpm scitepm

./build_generic_rpm eee-acpi

# Doesn't build without error just yet:
#./build_generic_rpm truecrypt

./build_generic_rpm eee-user-defaults

./build_generic_rpm eee-nologin

# boost 
#  - (needs bjam?) - maybe just let Fedora team do this one

