#! /bin/bash

# You've got to be root to do this and the module should 
# be in the same directory (which sucks - but it'll do until we've RPMed everything)

mkdir /lib/modules/`uname -r`/kernel/drivers/net/atl2
cp /mnt/live/drivers/atl2.ko /lib/modules/`uname -r`/kernel/drivers/net/atl2/
/sbin/depmod -a

# Do this as a force since the mirror repo in the ks 
# may have a slightly dated kernel (no big deal)
/sbin/modprobe -f atl2 
