#! /bin/bash

# ${setup}/live-install/fix-liveinst-script ${setup}

# Not necessary 
setup=${1:-/root/eee-setup}
liveuser=${2:-eeedora}

# Fix up mount and umount so that I can sudo them...	
echo '' >> /etc/sudoers
echo ${liveuser}'	localhost=NOPASSWD:mount,umount' >> /etc/sudoers
echo '' >> /etc/sudoers
# Done
