#! /bin/bash

# http://www.linux.org/docs/ldp/howto/Bash-Prog-Intro-HOWTO-12.html#ss12.2
# http://books.google.com/books?id=Qu6H8fnAvGoC&pg=PA99&lpg=PA99&dq=bash+default+values+%241&source=web&ots=CfmTbjtL5-&sig=3M-tjZACH6NhV97sudbLAmkUAN0#PPA99,M1
tarball=${1:-/root/eee_tarball}
liveuser=${2:-eeedora}

#  See : http://ubuntuforums.org/showthread.php?t=152274&page=3
# In /etc/inittab : Replace line : #1:2345:respawn:/sbin/mingetty tty1
# with #1:2345:respawn:/sbin/mingetty tty1 --autologin user
sed -i -e 's|^1:2345:respawn:/sbin/mingetty tty1$|& --autologin '${liveuser}'|' /etc/inittab

# http://www.grymoire.com/Unix/Sed.html#uh-0

# append to bash_profile:
cat ${tarball}/xdm/autologin-appendto-dot-bash_profile >> /home/${liveuser}/.bash_profile

