#! /bin/bash

tarball=${1:-/root/eee_tarball}
liveuser=${2:-eeedora}

# TODO : if *xdm or gdm is installed then don't do this...
#displaymanager=`rpm -qa *xdm gdm`

# ShowProgress "Autologin ${liveuser} with no password screen"
${tarball}/xdm/setup-nologin ${tarball} ${liveuser}

# xdm alternative :
# ${tarball}/xdm/setup-xdm ${tarball} ${liveuser}

# gdm alternative :
# ${tarball}/xdm/setup-gdm ${tarball} ${liveuser}
